describe('My First Test', () => {
    it('Visits the Kuverit', () => {
        cy.visit('https://app.kuverit.com')
        cy.contains('Sign In').click()
        cy.url().should('include', '/auth/login')
        cy.get('#identifier').type('free@mailinator.com').should('have.value', 'free@mailinator.com')
        cy.get('#password').type('bcdapps123')
        cy.get('#rememberme').click()
        cy.get('.flex > .px-6').click()
        cy.visit('https://app.kuverit.com/freelancer/project/create-invoice')
        cy.get('.css-15mtlmj-control').click()
        cy.wait(1000)
        cy.contains(/79/i).type('{enter}')
        cy.get('.css-7xxymi-StyledInput').type('100')
        cy.get('.mt-16 > .px-6').click()
    })
})